model:
    __type__: configs.Transformer_Config
    tmix: x060
    cmix: x060moe
    num_experts: 8
    ep_size: 8

    ctx_len: 4096
    n_layer: 32
    n_embd: 4096
    vocab_size: 65536

train:
    ckpt_path: '/share/moe_ckpt_full'
    load_partial: 1

    wandb: "finch-moe-upgrade"
    proj_suffix: "upgrade"

    data_type: "binidx"
    data_file: "/share/dataset_eval_boost"
    #validation_data_file: "/storage/data/minipile_validation/minipile_validation"
    #val_check_interval: 1.0
    my_exit_tokens: 501998874
    magic_prime: 122501

    save_every_n_epochs: 1

    lr_decay_type: cos
    lr_wait: 0
    lr_init: 8e-6
    lr_final: 0
    lr2_init: 8e-6
    lr2_final: 0
    warmup_steps: 10
    beta1: 0.95
    beta2: 0.99
    adam_eps: 1e-8
    weight_decay: 0 #.1

    devices: 8
    num_nodes: 2
    micro_bsz: 14
    accumulate_grad_batches: 1
    strategy: deepspeed_stage_1
    grad_cp: 1
    ds_bucket_mb: 200 # set to 2 for consumer GPUs, set to 200 for A100 / H100 (affects speed & vram usage)
